### ISSUE TITLE
Panic when creating NewWasiImportObjectForVersion with non empty string slices (wasi)

### ISSUE THREAD

**Issue by rusenask** [wasmerio/wasmer-go#127]
### Describe the bug

When using WASI import object and setting either args or env in the []string getting 

```
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
	panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 6 [running]:
testing.tRunner.func1.1(0x921ae0, 0xc00007d7d0)
	/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0000cd440)
	/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x921ae0, 0xc00007d7d0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/wasmerio/go-ext-wasm/wasmer.cNewWasmerWasiImportObject.func1(0xc00000e9c0, 0x0, 0xc00000e9e0, 0x1, 0xc00000ea00, 0x0, 0xc00000ea20, 0x0, 0xc00000ea20)
	/home/karolis/go/pkg/mod/github.com/wasmerio/go-ext-wasm@v0.3.2-0.20200309110852-0793478402af/wasmer/bridge.go:233 +0x65
github.com/wasmerio/go-ext-wasm/wasmer.cNewWasmerWasiImportObject(0xc00000e9c0, 0x0, 0xc00000e9e0, 0x1, 0xc00000ea00, 0x0, 0xc00000ea20, 0x0, 0xc000001980)
	/home/karolis/go/pkg/mod/github.com/wasmerio/go-ext-wasm@v0.3.2-0.20200309110852-0793478402af/wasmer/bridge.go:233 +0x7e
github.com/wasmerio/go-ext-wasm/wasmer.NewWasiImportObjectForVersion(0x0, 0x0, 0x0, 0x0, 0xc00007d680, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/home/karolis/go/pkg/mod/github.com/wasmerio/go-ext-wasm@v0.3.2-0.20200309110852-0793478402af/wasmer/wasi.go:101 +0x40d
```

Couldn't see any examples or tests using this feature in the PR here https://github.com/wasmerio/go-ext-wasm/pull/92/files, maybe I am using it wrong @Hywan ?

### Steps to reproduce

1. Try creating a `wasm.NewWasiImportObjectForVersion(wasiVersion, args, env, dirs, mappedDirs)` with non empty []string slices

Some code example:

```golang
	module, err := wasm.Compile(code)
	if err != nil {
		return nil, fmt.Errorf("failed to compile wasm module, error: %s", err)
	}
	wasiVersion := wasm.WasiGetVersion(module)

	var (
		args []string
		dirs []string
                env []string
		mappedDirs []wasm.MapDirEntry
	)
        env = append(env, "some-key=some-val")
        
	importObject := wasm.NewWasiImportObjectForVersion(wasiVersion, args, env, dirs, mappedDirs)
        // PANICS HERE ^ :) 
```

### Expected behavior

Not panic and those args or env variables should be available in the wasm module.

### Actual behavior

Can't create import object 

```
panic: runtime error: cgo argument has Go pointer to Go pointer
```

### Additional context

Version github.com/wasmerio/go-ext-wasm v0.3.2-0.20200309110852-0793478402af

**Comment by Hywan** [comment]
Problem solved since the project has been rewritten for the 1.0 :-).

I'm closing this issue.
