### ISSUE TITLE
instance.Close causes SIGABRT when WASM exported function is still running

### ISSUE THREAD

**Issue by vedhavyas** [wasmerio/wasmer-go#138]
Thanks for the bug report!

### Describe the bug
`instance.Close` causes `runtime: unknown pc` when a wasm exported function is still being executed.

The following is the full trace
```
 SIGABRT: abort
[2020-07-31 09:47:35] PC=0x7f1c97d40428 m=6 sigcode=18446744073709551610
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 0 [idle]:
[2020-07-31 09:47:35] runtime: unknown pc 0x7f1c97d40428
[2020-07-31 09:47:35] stack: frame={sp:0xc0004fb1a8, fp:0x0} stack=[0x7f1c6bb9ec28,0x7f1c6c39e828)
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] runtime: unknown pc 0x7f1c97d40428
[2020-07-31 09:47:35] stack: frame={sp:0xc0004fb1a8, fp:0x0} stack=[0x7f1c6bb9ec28,0x7f1c6c39e828)
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 73 [syscall]:
[2020-07-31 09:47:35] runtime.cgocall(0x1495fd0, 0xc0000a0bb0, 0x10)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/runtime/cgocall.go:133 +0x7a fp=0xc0000a0b80 sp=0xc0000a0b48 pc=0x41ad5a
[2020-07-31 09:47:35] github.com/wasmerio/go-ext-wasm/wasmer._Cfunc_wasmer_instance_call(0x45ac780, 0x3f8cd90, 0xc000036c40, 0x2, 0xc0003d2930, 0x1, 0xc000000000)
[2020-07-31 09:47:35] 	_cgo_gotypes.go:790 +0x6b fp=0xc0000a0bb0 sp=0xc0000a0b80 pc=0xfe2f8b
[2020-07-31 09:47:35] github.com/wasmerio/go-ext-wasm/wasmer.cWasmerInstanceCall(...)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/wasmerio/go-ext-wasm/wasmer/bridge.go:503
[2020-07-31 09:47:35] github.com/wasmerio/go-ext-wasm/wasmer.getExportsFromInstance.func2(0xc000128220, 0x2, 0x2, 0xc000268b40, 0x119, 0x207, 0x1)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/wasmerio/go-ext-wasm/wasmer/instance.go:365 +0x4e6 fp=0xc0000a0e70 sp=0xc0000a0bb0 pc=0xfe4666
[2020-07-31 09:47:35] github.com/centrifuge/go-centrifuge/documents.executeWASM.func1(0xc00027e690, 0xc0003ef3b0, 0xc0003ef320, 0xc00027e620, 0xc000042300)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/documents/compute_fields.go:101 +0x507 fp=0xc0000a0fb8 sp=0xc0000a0e70 pc=0x1467c37
[2020-07-31 09:47:35] runtime.goexit()
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000a0fc0 sp=0xc0000a0fb8 pc=0x4822b1
[2020-07-31 09:47:35] created by github.com/centrifuge/go-centrifuge/documents.executeWASM
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/documents/compute_fields.go:85 +0x68b
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 1 [chan receive]:
[2020-07-31 09:47:35] testing.(*T).Run(0xc000186000, 0x176f839, 0x10, 0x1902738, 0x1)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/testing/testing.go:1043 +0x699
[2020-07-31 09:47:35] testing.runTests.func1(0xc000186000)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/testing/testing.go:1284 +0xa7
[2020-07-31 09:47:35] testing.tRunner(0xc000186000, 0xc00052db90)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/testing/testing.go:991 +0x1ec
[2020-07-31 09:47:35] testing.runTests(0xc0003d1260, 0x2621d00, 0x85, 0x85, 0x0)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/testing/testing.go:1282 +0x528
[2020-07-31 09:47:35] testing.(*M).Run(0xc000248700, 0x0)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/testing/testing.go:1199 +0x300
[2020-07-31 09:47:35] github.com/centrifuge/go-centrifuge/documents.TestMain(0xc000248700)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/documents/coredocument_test.go:71 +0x94c
[2020-07-31 09:47:35] main.main()
[2020-07-31 09:47:35] 	_testmain.go:398 +0x334
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 19 [select]:
[2020-07-31 09:47:35] github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc00026c540)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ipfs/go-log/writer/writer.go:71 +0x1a6
[2020-07-31 09:47:35] created by github.com/ipfs/go-log/writer.NewMirrorWriter
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ipfs/go-log/writer/writer.go:36 +0x134
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 6 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0001c2700)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:91 +0x16b
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x7c0
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 22 [chan receive]:
[2020-07-31 09:47:35] github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0002c7320, 0xc0002c7260)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xdf
[2020-07-31 09:47:35] created by github.com/rjeczalik/notify.newNonrecursiveTree
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x1b9
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 23 [chan receive]:
[2020-07-31 09:47:35] github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0002c7320, 0xc0002c72c0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x69
[2020-07-31 09:47:35] created by github.com/rjeczalik/notify.newNonrecursiveTree
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x1e5
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 24 [chan receive]:
[2020-07-31 09:47:35] github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x272b4c0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/metrics/meter.go:289 +0xb3
[2020-07-31 09:47:35] created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/metrics/meter.go:70 +0x153
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 25 [select]:
[2020-07-31 09:47:35] github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0003582d0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:278 +0x614
[2020-07-31 09:47:35] created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:262 +0x519
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 26 [chan receive]:
[2020-07-31 09:47:35] github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00037e860)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x161
[2020-07-31 09:47:35] created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0xd2
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 27 [chan receive]:
[2020-07-31 09:47:35] github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00037e860)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x161
[2020-07-31 09:47:35] created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0xd2
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 29 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0001aeb60)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x1cb
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x2f4
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 30 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0003583c0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session_util.go:189 +0x7bc
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.newSession
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session.go:93 +0x4c8
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 7 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0001c2700)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0x17f
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x7e5
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 8 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0001c2700)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:836 +0x370
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:155 +0x94d
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 9 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0001c2700)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:773 +0x1ed
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:156 +0x972
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 10 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0001ae000)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x1cb
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x2f4
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 11 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc000358000)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session_util.go:189 +0x7bc
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.newSession
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session.go:93 +0x4c8
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 31 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0001c28c0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:91 +0x16b
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x7c0
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 32 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0001c28c0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0x17f
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x7e5
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 33 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0001c28c0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:836 +0x370
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:155 +0x94d
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 34 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0001c28c0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:773 +0x1ed
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:156 +0x972
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 72 [runnable]:
[2020-07-31 09:47:35] internal/poll.(*FD).readUnlock(0xc0001395c0)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/internal/poll/fd_mutex.go:230 +0x6b
[2020-07-31 09:47:35] internal/poll.(*FD).Read(0xc0001395c0, 0xc001a34000, 0x17842a, 0x17842a, 0x17822a, 0x0, 0x0)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/internal/poll/fd_unix.go:181 +0x29a
[2020-07-31 09:47:35] os.(*File).read(...)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/os/file_unix.go:263
[2020-07-31 09:47:35] os.(*File).Read(0xc000010190, 0xc001a34000, 0x17842a, 0x17842a, 0x17842a, 0x17842a, 0xc0001bba70)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/os/file.go:116 +0xa7
[2020-07-31 09:47:35] bytes.(*Buffer).ReadFrom(0xc0001bbac0, 0x1ada720, 0xc000010190, 0x272bc20, 0xc0002031f8, 0xc000203230)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/bytes/buffer.go:204 +0x159
[2020-07-31 09:47:35] io/ioutil.readAll(0x1ada720, 0xc000010190, 0x17842a, 0x0, 0x0, 0x0, 0x0, 0x0)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/io/ioutil/ioutil.go:36 +0x157
[2020-07-31 09:47:35] io/ioutil.ReadFile(0x179868b, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/io/ioutil/ioutil.go:73 +0x12f
[2020-07-31 09:47:35] github.com/centrifuge/go-centrifuge/documents.wasmLoader(0xc0002b4ea0, 0x179868b, 0x32, 0xc000036d40, 0x15a4600, 0xc000036d60)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/documents/compute_fields_test.go:21 +0x56
[2020-07-31 09:47:35] github.com/centrifuge/go-centrifuge/documents.Test_executeWASM(0xc0002b4ea0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/documents/compute_fields_test.go:140 +0x250
[2020-07-31 09:47:35] testing.tRunner(0xc0002b4ea0, 0x1902738)
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/testing/testing.go:991 +0x1ec
[2020-07-31 09:47:35] created by testing.(*T).Run
[2020-07-31 09:47:35] 	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/testing/testing.go:1042 +0x661
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 39 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0001c3180)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:91 +0x16b
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x7c0
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 69 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0001aee00)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x1cb
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x2f4
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 70 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0003580f0)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session_util.go:189 +0x7bc
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.newSession
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session.go:93 +0x4c8
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 40 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0001c3180)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0x17f
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x7e5
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 41 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0001c3180)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:836 +0x370
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:155 +0x94d
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] goroutine 42 [select]:
[2020-07-31 09:47:35] github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0001c3180)
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:773 +0x1ed
[2020-07-31 09:47:35] created by github.com/syndtr/goleveldb/leveldb.openDB
[2020-07-31 09:47:35] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:156 +0x972
[2020-07-31 09:47:35] 
[2020-07-31 09:47:35] rax    0x0
[2020-07-31 09:47:35] rbx    0x7f1c6c39f060
[2020-07-31 09:47:35] rcx    0x7f1c97d40428
[2020-07-31 09:47:35] rdx    0x6
[2020-07-31 09:47:35] rdi    0x7324
[2020-07-31 09:47:35] rsi    0x732a
[2020-07-31 09:47:35] rbp    0xc0004fb360
[2020-07-31 09:47:35] rsp    0xc0004fb1a8
[2020-07-31 09:47:35] r8     0x0
[2020-07-31 09:47:35] r9     0x0
[2020-07-31 09:47:35] r10    0x8
[2020-07-31 09:47:35] r11    0x206
[2020-07-31 09:47:35] r12    0x7f1c6c39e1b0
[2020-07-31 09:47:35] r13    0x30
[2020-07-31 09:47:35] r14    0xb
[2020-07-31 09:47:35] r15    0xb
[2020-07-31 09:47:35] rip    0x7f1c97d40428
[2020-07-31 09:47:35] rflags 0x206
[2020-07-31 09:47:35] cs     0x33
[2020-07-31 09:47:35] fs     0x0
[2020-07-31 09:47:35] gs     0x0
```
If I don't call `instance.Close`, the function continues to run. Ideally, I would want to stop the function execution.

### Steps to reproduce
1. I have created a WASM the exports a function, which on execution does an infinite loop
2. I start the execution, and while the function is being executed, I call `instance.Close`
3. This see `SIGABRT: abort` with the above trace.

Unfortunately, I'm not able to reproduce this on my Mac but was able to reproduce this on Travis CI. Here is the system info of the same:

```
Build language: go
Build dist: xenial
Build id: 177931567
Job id: 366995277
Runtime kernel version: 4.15.0-1077-gcp
travis-build version: 6a7410c5
Build image provisioning date and time
Wed Jun 24 13:36:52 UTC 2020
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
Systemd Version
systemd 229
Cookbooks Version
3f92a99 https://github.com/travis-ci/travis-cookbooks/tree/3f92a99
git version
git version 2.27.0
bash version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

Here is the link to the test case on Travis:
https://travis-ci.com/github/centrifuge/go-centrifuge/jobs/366995277#L2328

### Expected behavior
on-call to `instance.Close`, the instance should stop the executing WASM function 

### Actual behavior
program exists

**Comment by Hywan** [comment]
Hello,

It's not an expected behavior to close an instance while it is running. What is your usecase?

**Comment by vedhavyas** [comment]
@Hywan we want to limit the WASM runtime to specific time. lets say 30 sec. We tried to stop the execution once the timeout

**Comment by Hywan** [comment]
The best way to achieve that is through gas limit. Every operation has a cost, and once credit is zero, the runtime stops running. Would it solve your issue?

**Comment by rusenask** [comment]
Is gas limit available in the latest version of wasmer-go?

**Comment by vedhavyas** [comment]
Cool!
I was playing with gas limit with perlin life. Didn't realize wasmer has gas limit options as well. Can you point me to any docs or examples  @Hywan

**Comment by Hywan** [comment]
It's not yet available, but we are planning to add it. It works on Wasmer, but it's not yet available in the C API (see https://github.com/wasmerio/wasmer/issues/2025).

Closing this for the moment :-).
